"""Generate parametric bracket-matrix devices from the locked mark spec.

The matrix device is the mark's construction opened to other words:
  - up to 4 letters  -> the 2x2 grid (the mark's own geometry)
  - 5 to 9 letters   -> a 3x3 grid at the same cell pitch
  - unused slots are filled with dots (the favicon idiom)

Everything inherits from the locked spec in build-logos.py: same face
(Latin Modern Mono Light 10 Bold), same cap height, spread, bracket
stroke ratio and arm length, same 216-unit ink height normalisation --
so any device sits next to the mark as an equal-weight sibling.

Usage:  python build-matrix.py JOIN RESEARCH ...
Writes: assets/matrix/oqts-matrix-<word>.svg (+ -reverse) per word.
"""
import os
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DESIGN = os.path.dirname(ROOT)
FONTS = os.path.join(ROOT, "fonts")
OUT = os.path.join(DESIGN, "assets", "matrix")
os.makedirs(OUT, exist_ok=True)

# ---- locked spec, inherited from build-logos.py (keep in sync) ----
H = 216.0            # ink height every device normalises to
SPREAD = 100.0       # centre-to-centre cell pitch
CAP_U = 62.0         # cap height of matrix letters, pre-scale units
BR = 16.0 / 14.0     # bracket stroke : glyph stem
MARK_STEM = 0.1352   # stem ratio measured by analyse-fonts.py
EDGE_INSET = 50.0    # bracket edge to first cell centre
DOT_R = 11.0         # dot radius; reads at the letters' optical weight

MARK_FONT = os.path.join(FONTS, "lmm-lmmonolt10-bold.otf")
NAVY, PAPER, WHITE = "#002147", "#F4EDDC", "#FFFFFF"
IVORY = "#FBF8F1"
PAD = 16.0
CIRCLE_KEEP = 0.92   # circlesafe: ink diagonal held to 92% of the crop circle


class Face:
    def __init__(self, path, cap_ratio):
        self.tt = TTFont(path, lazy=True)
        self.gs = self.tt.getGlyphSet()
        self.upem = self.tt["head"].unitsPerEm
        self.cmap = self.tt.getBestCmap()
        self.hmtx = self.tt["hmtx"]
        self.cap = cap_ratio * self.upem

    def name(self, ch):
        return self.cmap[ord(ch)]

    def advance(self, ch):
        return self.hmtx[self.name(ch)][0]

    def path(self, ch):
        pen = SVGPathPen(self.gs)
        self.gs[self.name(ch)].draw(pen)
        return pen.getCommands()


face = Face(MARK_FONT, 0.61)


def glyph_path(ch, x, baseline_y):
    s = CAP_U / face.cap
    dx = x - face.advance(ch) * s / 2
    d = face.path(ch)
    return (f'<path d="{d}" transform="translate({dx:.3f},{baseline_y:.3f}) '
            f'scale({s:.6f},{-s:.6f})"/>')


def build_matrix(word, colour):
    """Bracketed n x n letter matrix, ink normalised to H. Returns (frag, w, h)."""
    word = word.upper()
    if not (1 <= len(word) <= 9):
        raise SystemExit(f"'{word}': need 1-9 letters")
    n = 2 if len(word) <= 4 else 3

    stem = MARK_STEM * CAP_U
    w = stem * BR
    tick = 22.0 * (w / 16.0)
    span = n * SPREAD                       # bracket inner span: 200 / 300
    left, right = 40.0, 40.0 + span
    edge = left - w / 2.0
    k = H / (span + w)

    brackets = (f'<g fill="none" stroke="{colour}" stroke-width="{w:.3f}">'
                f'<path d="M {left+tick:.2f} {left:.2f} L {left:.2f} {left:.2f} '
                f'L {left:.2f} {right:.2f} L {left+tick:.2f} {right:.2f}"/>'
                f'<path d="M {right-tick:.2f} {left:.2f} L {right:.2f} {left:.2f} '
                f'L {right:.2f} {right:.2f} L {right-tick:.2f} {right:.2f}"/></g>')

    cells = []
    for i in range(n * n):
        row, col = divmod(i, n)
        cx = left + EDGE_INSET + col * SPREAD
        cy = left + EDGE_INSET + row * SPREAD
        cells.append((word[i] if i < len(word) else None, cx, cy))

    parts = []
    for ch, cx, cy in cells:
        if ch is None:
            parts.append(f'<circle cx="{cx:.2f}" cy="{cy:.2f}" r="{DOT_R}"/>')
        elif ch != " ":
            parts.append(glyph_path(ch, cx, cy + CAP_U / 2.0))

    frag = (f'<g transform="scale({k:.6f}) translate({-edge:.3f},{-edge:.3f})">'
            f'{brackets}<g fill="{colour}">{"".join(parts)}</g></g>')
    return frag, H, H


def emit(name, word, body, tw, th):
    doc = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {tw:.2f} {th:.2f}" '
           f'width="{tw:.2f}" height="{th:.2f}" role="img" aria-label="{word} matrix">'
           f'<!-- OQTS matrix device "{word}". Generated by lab/tools/build-matrix.py; '
           f'construction inherited from the locked mark spec. -->{body}</svg>')
    with open(os.path.join(OUT, name), "w") as fh:
        fh.write(doc + "\n")
    print(f"  {name}")


def write(word):
    for suffix, colour in [("", NAVY), ("-reverse", PAPER)]:
        frag, w, h = build_matrix(word, colour)
        body = f'<g transform="translate({PAD},{PAD})">{frag}</g>'
        emit(f"oqts-matrix-{word.lower()}{suffix}.svg", word,
             body, w + 2 * PAD, h + 2 * PAD)

    # circlesafe: opaque ground, ink diagonal cleared for a circular crop
    for suffix, colour, ground in [("-on-white", NAVY, WHITE),
                                   ("-on-ivory", NAVY, IVORY),
                                   ("-on-paper", NAVY, PAPER),
                                   ("-on-navy", PAPER, NAVY)]:
        frag, w, h = build_matrix(word, colour)
        side = h * 2 ** 0.5 / CIRCLE_KEEP
        pad = (side - h) / 2.0
        body = (f'<rect width="{side:.2f}" height="{side:.2f}" fill="{ground}"/>'
                f'<g transform="translate({pad:.3f},{pad:.3f})">{frag}</g>')
        emit(f"oqts-matrix-{word.lower()}{suffix}-circlesafe.svg", word,
             body, side, side)


words = sys.argv[1:] or ["JOIN"]
for word_arg in words:
    write(word_arg)
