"""Generate fonts/fonts.css and fonts/catalog.js from whatever is in fonts/.

This is what makes adding a face a two-step job: drop the .ttf/.otf into fonts/,
then run tools/refresh-fonts.sh. Nothing in wordmark.html needs editing.

Google splits weights into separate family names ("Poppins SemiBold", "DM Mono
Medium"), which breaks CSS weight selection, so family names are normalised back
to the base name and the numeric usWeightClass carries the weight.
"""
import glob
import json
import os
import re

from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONTS = os.path.join(ROOT, "fonts")

SUFFIXES = ["Extra Light", "ExtraLight", "UltraLight", "SemiBold", "Semi Bold",
            "DemiBold", "Extra Bold", "ExtraBold", "Thin", "Light", "Regular",
            "Book", "Medium", "Bold", "Black", "Heavy"]
SUFFIX_RE = re.compile(r"\s+(" + "|".join(SUFFIXES) + r")$", re.I)

metrics = {m["file"]: m for m in json.load(open(os.path.join(FONTS, "metrics.json")))}
qshape = json.load(open(os.path.join(FONTS, "qshape.json")))


def base_family(name):
    prev = None
    while prev != name:                     # "Latin Modern Mono Light" -> "Latin Modern Mono"
        prev = name
        name = SUFFIX_RE.sub("", name).strip()
    return name


families, seen = {}, {}
for path in sorted(glob.glob(os.path.join(FONTS, "*.ttf"))) + \
            sorted(glob.glob(os.path.join(FONTS, "*.otf"))):
    fn = os.path.basename(path)
    m = metrics.get(fn)
    if not m:
        continue                            # analyser rejected it (H not two stems)
    try:
        tt = TTFont(path, lazy=True, fontNumber=0)
        mono = bool(tt["post"].isFixedPitch)
        tt.close()
    except Exception:
        continue

    fam = base_family(m["family"])
    w = m["weight"]
    if (fam, w) in seen:
        continue
    seen[(fam, w)] = fn

    q = qshape.get(fn, {})
    families.setdefault(fam, {"family": fam, "mono": mono, "weights": {}})
    families[fam]["weights"][w] = {
        "file": fn,
        "cap": m["capRatio"],
        "stem": m["stemRatio"],
        "o": m["oAspect"],
        "crossQ": bool(q.get("crossing", False)),
        "fill": q.get("counterFill"),
        "reach": q.get("reach"),
    }

# ---- fonts.css ----
css = ["/* generated by tools/build-catalog.py - do not edit by hand */"]
for fam in sorted(families):
    for w in sorted(families[fam]["weights"]):
        f = families[fam]["weights"][w]["file"]
        css.append(f"@font-face{{font-family:'{fam}';src:url('{f}');"
                   f"font-weight:{w};font-display:block}}")
with open(os.path.join(FONTS, "fonts.css"), "w") as fh:
    fh.write("\n".join(css) + "\n")

# ---- catalog.js ----
out = []
for fam in sorted(families):
    e = families[fam]
    ws = e["weights"]
    # the weight whose stem best matches the mark's 14/62, and the next lighter one
    mark_w = min(ws, key=lambda w: abs(ws[w]["stem"] - 14 / 62))
    lighter = [w for w in ws if w < mark_w]
    text_w = max(lighter) if lighter else mark_w
    out.append({
        "family": fam, "mono": e["mono"],
        "markW": mark_w, "textW": text_w,
        "cap": ws[mark_w]["cap"], "textCap": ws[text_w]["cap"],
        "stem": ws[mark_w]["stem"], "o": ws[mark_w]["o"],
        "crossQ": ws[mark_w]["crossQ"],
        "weights": sorted(ws),
    })

out.sort(key=lambda e: (not e["crossQ"], abs(e["o"] - 1.0) + abs(e["stem"] - 14 / 62) / (14 / 62)))
with open(os.path.join(FONTS, "catalog.js"), "w") as fh:
    fh.write("window.OQTS_FONTS = " + json.dumps(out, indent=1) + ";\n")

print(f"{len(families)} families, {len(seen)} faces")
print(f"crossing-Q families: {sum(1 for e in out if e['crossQ'])}")
print(f"\n{'family':26s} {'mark':>5s} {'text':>5s} {'O':>6s} {'stem':>6s}  crossQ mono")
print("-" * 66)
for e in out[:16]:
    print(f"{e['family'][:26]:26s} {e['markW']:>5} {e['textW']:>5} "
          f"{e['o']:>6.3f} {e['stem']:>6.3f}  {'yes' if e['crossQ'] else ' - ':>6s} "
          f"{'mono' if e['mono'] else ''}")
